import { AfterViewInit, OnChanges, QueryList, SimpleChanges } from '@angular/core';
import { ColumnComponent } from './column.component';
import * as GC from '@grapecity/spread-sheets';
export declare class WorksheetComponent implements OnChanges, AfterViewInit {
    private sheet;
    columns?: QueryList<ColumnComponent>;
    rowCount?: number;
    colCount?: number;
    dataSource: any;
    name?: string;
    frozenColumnCount?: number;
    frozenRowCount?: number;
    frozenTrailingRowCount?: number;
    frozenTrailingColumnCount?: number;
    allowCellOverflow?: boolean;
    frozenlineColor?: string;
    sheetTabColor?: string;
    selectionPolicy?: number;
    selectionUnit?: number;
    zoom?: number;
    currentTheme?: string;
    clipBoardOptions?: number;
    rowHeaderVisible?: boolean;
    colHeaderVisible?: boolean;
    rowHeaderAutoText?: number;
    colHeaderAutoText?: number;
    rowHeaderAutoTextIndex?: number;
    colHeaderAutoTextIndex?: number;
    isProtected?: boolean;
    showRowOutline?: boolean;
    showColumnOutline?: boolean;
    selectionBackColor?: string;
    selectionBorderColor?: string;
    defaultStyle?: GC.Spread.Sheets.Style;
    rowOutlineInfo?: any[];
    columnOutlineInfo?: any[];
    autoGenerateColumns?: boolean;
    constructor();
    onAttached(): void;
    getSheet(): GC.Spread.Sheets.Worksheet;
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
}
